[package]
name = "solana-deserialize-utils"
description = "Solana deserialization helpers"
documentation = "https://docs.rs/solana-deserialize-utils"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
serde = { workspace = true }

[dev-dependencies]
bincode = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
