[package]
name = "solana-stake-interface"
version = "2.2.0"
description = "Instructions and constructors for the Stake program"
readme = "README.md"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["rlib"]

[package.metadata.solana]
program-id = "Stake11111111111111111111111111111111111111"

[dependencies]
borsh = { workspace = true, optional = true }
borsh0-10 = { workspace = true, optional = true }
num-traits = { workspace = true }
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
solana-decode-error = { workspace = true }
solana-clock = { workspace = true }
solana-cpi = { workspace = true, optional = true }
solana-frozen-abi = { workspace = true, features = ["frozen-abi"], optional = true }
solana-frozen-abi-macro = { workspace = true, features = ["frozen-abi"], optional = true }
solana-instruction = { workspace = true, features = ["std"] }
solana-program-error = { workspace = true }
solana-pubkey = { workspace = true, default-features = false }
solana-sdk-ids = { workspace = true }
solana-system-interface = { workspace = true }
solana-sysvar-id = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
bincode = { workspace = true }
solana-borsh = { workspace = true }
static_assertions = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[features]
bincode = [
    "dep:solana-cpi",
    "solana-instruction/bincode",
    "solana-instruction/serde",
    "solana-system-interface/bincode",
    "serde"
]
borsh = [
    "dep:borsh",
    "dep:borsh0-10",
    "solana-instruction/borsh",
    "solana-program-error/borsh",
    "solana-pubkey/borsh"
]
frozen-abi = [
    "dep:solana-frozen-abi",
    "dep:solana-frozen-abi-macro",
    "solana-instruction/frozen-abi",
    "solana-pubkey/frozen-abi"
]
serde = ["dep:serde", "dep:serde_derive", "solana-pubkey/serde"]
