[package]
name = "solana-svm-example-json-rpc-server"
description = "Solana SVM Example JSON RPC Server"
documentation = "https://docs.rs/solana-svm"
version = "2.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
bincode = "1.3.3"
borsh = { version = "1.5.1", features = ["derive"] }
bs58 = "0.5.1"
bzip2 = "0.4.4"
clap = "2.33.1"
crossbeam-channel = "0.5.13"
dashmap = { version = "5.5.3", features = ["rayon", "raw-api"] }
env_logger = "0.9.3"
flate2 = "1.0.30"
home = "0.5"
im = { version = "15.1.0", features = ["rayon", "serde"] }
itertools = "0.12.1"
jsonrpc-core = "18.0.0"
jsonrpc-core-client = "18.0.0"
jsonrpc-derive = "18.0.0"
jsonrpc-http-server = "18.0.0"
lazy_static = "1.5.0"
libc = "0.2.155"
libsecp256k1 = "0.6.0"
log = "0.4.22"
lz4 = "1.26.0"
num_cpus = "1.16.0"
percentage = "0.1.0"
prost = "0.11.9"
qualifier_attr = { version = "0.2.2", optional = true }
rand = "0.8.5"
rayon = "1.10.0"
regex = "1.10.5"
serde = { version = "1.0.204", features = ["rc"] }
serde_derive = "1.0.204"
serde_json = "1.0.120"
serde_yaml = "0.9.34"
solana-account-decoder = { path = "../../../account-decoder", version = "2.1.0" }
solana-accounts-db = { path = "../../../accounts-db", version = "2.1.0" }
solana-bpf-loader-program = { path = "../../../programs/bpf_loader", version = "2.1.0" }
solana-client = { path = "../../../client", version = "2.1.0" }
solana-compute-budget = { path = "../../../compute-budget", version = "2.1.0" }
solana-compute-budget-program = { path = "../../../programs/compute-budget", version = "2.1.0" }
solana-core = { path = "../../../core", version = "2.1.0" }
solana-frozen-abi = { path = "../../../frozen-abi", version = "2.1.0", optional = true }
solana-frozen-abi-macro = { path = "../../../frozen-abi/macro", version = "2.1.0", optional = true }
solana-geyser-plugin-manager = { path = "../../../geyser-plugin-manager", version = "2.1.0" }
solana-gossip = { path = "../../../gossip", version = "2.1.0" }
solana-loader-v4-program = { path = "../../../programs/loader-v4", version = "2.1.0" }
solana-log-collector = { path = "../../../log-collector", version = "2.1.0" }
solana-logger = { path = "../../../logger", version = "2.1.0" }
solana-measure = { path = "../../../measure", version = "2.1.0" }
solana-metrics = { path = "../../../metrics", version = "2.1.0" }
solana-perf = { path = "../../../perf", version = "2.1.0" }
solana-program-runtime = { path = "../../../program-runtime", version = "2.1.0" }
solana-rpc = { path = "../../../rpc", version = "2.1.0" }
solana-rpc-client = { path = "../../../rpc-client", version = "2.1.0" }
solana-rpc-client-api = { path = "../../../rpc-client-api", version = "2.1.0" }
solana-sdk = { path = "../../../sdk", version = "2.1.0" }
solana-stake-program = { path = "../../../programs/stake", version = "2.1.0" }
solana-svm = { path = "../..", version = "2.1.0" }
solana-svm-conformance = { path = "../../../svm-conformance", version = "2.1.0" }
solana-system-program = { path = "../../../programs/system", version = "2.1.0" }
solana-timings = { path = "../../../timings", version = "2.1.0" }
solana-transaction-status = { path = "../../../transaction-status", version = "2.1.0" }
solana-type-overrides = { path = "../../../type-overrides", version = "2.1.0" }
solana-version = { path = "../../../version", version = "2.1.0" }
solana-vote = { path = "../../../vote", version = "2.1.0" }
spl-token-2022 = { version = "=4.0.0", features = ["no-entrypoint"] }
strum = { version = "0.24", features = ["derive"] }
symlink = "0.1.0"
tar = "0.4.41"
tempfile = "3.10.1"
thiserror = "1.0.63"
tokio = { version = "1.29.1", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec", "compat"] }
yaml-rust = "0.4"
zstd = "0.11.2"

[patch.crates-io]
solana-program = { path = "../../../sdk/program", version = "2.1.0" }
solana-zk-token-sdk = { path = "../../../zk-token-sdk", version = "2.1.0" }

# These features are needed for CI
[features]
dummy-for-ci-check = []
frozen-abi = []

[workspace]
