[package]
name = "solana-sbf-rust-dep-crate"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
readme = false

[dependencies]
byteorder = { workspace = true }
solana-program = { workspace = true }

[lib]
crate-type = ["cdylib"]
