[package]
name = "solana-sbf-rust-128bit-dep"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[dependencies]

[lints]
workspace = true
