too-many-arguments-threshold = 9

# Set the result_large_err lint threshold based on the current sizes as of May 21 2025.
# solana_rpc_client_api::client_error::Error is 256 bytes
# solana_tps_client::TpsClientError uses the ClientError (above) and is 264 bytes
large-error-threshold = 265

# Disallow specific methods from being used
disallowed-methods = [
    { path = "std::net::UdpSocket::bind", reason = "Use solana_net_utils::bind_with_config, bind_to, etc instead for proper socket configuration." },
    { path = "tokio::net::UdpSocket::bind", reason = "Use solana_net_utils::bind_to_async or bind_to_with_config_non_blocking instead for proper socket configuration." },
    { path = "lazy_static::initialize", reason = "Deprecated. Use std::{cell::{LazyCell, OnceCell}, sync::{LazyLock, OnceLock}} as appropriate." }
]

disallowed-macros = [
    { path = "solana_sdk::saturating_add_assign", reason = "Deprecated. Use std::num::Saturating<T> instead." },
    { path = "lazy_static::lazy_static", reason = "Deprecated. Use std::{cell::{LazyCell, OnceCell}, sync::{LazyLock, OnceLock}} as appropriate." },
]
