[package]
name = "solana-lattice-hash"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
description = "Solana Lattice Hash"
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[[bench]]
harness = false
name = "bench_lt_hash"

[[bench]]
harness = false
name = "bench_batch"

[dependencies]
base64 = { workspace = true }
blake3 = { workspace = true }
bs58 = { workspace = true }
bytemuck = { workspace = true, features = ["must_cast"] }

[dev-dependencies]
criterion = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
solana-lattice-hash = { path = ".", features = ["agave-unstable-api"] }

[features]
agave-unstable-api = []

[lints]
workspace = true
