[package]
name = "solana-stake-program"
description = "Solana Stake program"
documentation = "https://docs.rs/solana-stake-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
log = { workspace = true }
solana-config-program = { workspace = true }
solana-feature-set = { workspace = true }
solana-log-collector = { workspace = true }
solana-program-runtime = { workspace = true }
solana-pubkey = { workspace = true }
solana-sdk = { workspace = true }
solana-type-overrides = { workspace = true }
solana-vote-program = { workspace = true, default-features = false }

[dev-dependencies]
assert_matches = { workspace = true }
criterion = { workspace = true }
proptest = { workspace = true }
solana-compute-budget = { workspace = true }
solana-logger = { workspace = true }
test-case = { workspace = true }

[features]
default = ["metrics"]
metrics = ["solana-vote-program/metrics"]

[lib]
crate-type = ["lib"]
name = "solana_stake_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bench]]
name = "stake"
harness = false

[lints]
workspace = true
