[package]
name = "solana-sbf-rust-many-args-dep"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[dependencies]
solana-msg = { workspace = true }
solana-program = { workspace = true }

[lints]
workspace = true
