[package]
name = "solana-sbf-rust-128bit"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[lib]
crate-type = ["cdylib"]

[dependencies]
solana-program-entrypoint = { workspace = true }
solana-sbf-rust-128bit-dep = { workspace = true }

[lints]
workspace = true
