[build]
rustflags = [
    "-g",
    "-Cpasses=sancov-module",
    "-Cllvm-args=-sanitizer-coverage-inline-8bit-counters",
    "-Cllvm-args=-sanitizer-coverage-level=4",
    "-Cllvm-args=-sanitizer-coverage-pc-table",
    "-Cllvm-args=-sanitizer-coverage-trace-compares",
    "-Clink-dead-code",
    "-Cforce-frame-pointers=yes",
    "-Ctarget-feature=-crt-static",
]


[target.aarch64-apple-darwin]
rustflags = [
    "-g",
    "-Cpasses=sancov-module",
    "-Cllvm-args=-sanitizer-coverage-inline-8bit-counters",
    "-Cllvm-args=-sanitizer-coverage-pc-table",
    "-Cllvm-args=-sanitizer-coverage-trace-compares",
    "-Clink-dead-code",
    "-Cforce-frame-pointers=yes",
    "-Ctarget-feature=-crt-static",
]