[package]
name = "solana-secp256k1-instruction"
description = "Instructions for the Solana Secp256k1 native program."
documentation = "https://docs.rs/solana-secp256k1-instruction"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true, optional = true }
digest = { workspace = true }
libsecp256k1 = { workspace = true, features = ["hmac"] }
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
sha3 = { workspace = true }
solana-feature-set = { workspace = true }
solana-instruction = { workspace = true, features = ["std"] }
solana-precompile-error = { workspace = true }
solana-pubkey = { workspace = true, optional = true }

[dev-dependencies]
anyhow = { workspace = true }
hex = { workspace = true }
rand0-7 = { workspace = true }
solana-hash = { workspace = true }
solana-logger = { workspace = true }
solana-program = { path = "../program" }
solana-sdk = { path = ".." }
solana-secp256k1-instruction = { path = ".", features = ["dev-context-only-utils"] }

[features]
bincode = ["dep:bincode", "dep:solana-pubkey", "serde"]
dev-context-only-utils = ["bincode"]
serde = ["dep:serde", "dep:serde_derive"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]
