[package]
name = "solana-feature"
description = "Solana runtime features."
documentation = "https://docs.rs/solana-feature"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
solana-account-info = { workspace = true, optional = true }
solana-instruction = { workspace = true, optional = true }
solana-program-error = { workspace = true, optional = true }
solana-pubkey = { workspace = true }
solana-rent = { workspace = true, optional = true }
solana-sdk-ids = { workspace = true }
solana-system-interface = { workspace = true, optional = true, features = [
    "bincode",
] }

[dev-dependencies]
solana-feature = { path = ".", features = ["dev-context-only-utils"] }

[features]
bincode = [
    "dep:bincode",
    "dep:solana-account-info",
    "dep:solana-instruction",
    "dep:solana-program-error",
    "dep:solana-rent",
    "dep:solana-system-interface",
    "serde",
]
dev-context-only-utils = ["bincode"]
serde = ["dep:serde", "dep:serde_derive"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true
