[package]
name = "solana-sbf-rust-invoked-dep"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[lib]
crate-type = ["lib"]

[dependencies]
solana-instruction = { workspace = true }
solana-pubkey = { workspace = true }

[lints]
workspace = true
