[package]
name = "solana-merkle-tree"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
description = "Solana Merkle Tree"
documentation = "https://docs.rs/solana-merkle-tree"
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[lib]
crate-type = ["lib"]
name = "solana_merkle_tree"

[dependencies]
solana-hash = { workspace = true }
solana-sha256-hasher = { workspace = true }

[dev-dependencies]
hex = { workspace = true }

[features]
agave-unstable-api = []

[lints]
workspace = true
