[package]
name = "solana-sbf-rust-direct-account-pointers"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[lib]
crate-type = ["cdylib"]

[dependencies]
solana-account-info = { workspace = true }
solana-account-view = { workspace = true }
solana-address = { workspace = true }
solana-cpi = { workspace = true }
solana-program-entrypoint = { workspace = true }
solana-program-error = { workspace = true }

[lints]
workspace = true
