[package]
name = "solana-sbf-rust-secp256k1-recover"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
k256 = { workspace = true, features = ["ecdsa"] }
solana-program = { workspace = true }
solana-secp256k1-recover = { workspace = true }

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true
