# Supported fields: ledger, identity, entrypoint, known_validators, rpc_port, log
# Precedence: CLI arguments > config file > defaults

ledger = "/mnt/ledger"
identity = "/mnt/identity.json"
entrypoint = [
  "entrypoint.devnet.solana.com:8001",
  "entrypoint2.devnet.solana.com:8001",
]
known_validators = [
  "7XSYv5sHvBt1Vd7Z7SF4K3tiTnxaAEZXQ6oPD58QzA8s",
]
rpc_port = 8899
log = "/var/log/agave-validator/devnet.log"


