[package]
name = "solana-sbf-rust-account-mem-deprecated"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[lib]
crate-type = ["cdylib"]

[dependencies]
solana-account-info = { workspace = true }
solana-program = { workspace = true }
solana-program-error = { workspace = true }
solana-program-memory = { workspace = true }
solana-pubkey = { workspace = true }

[lints]
workspace = true
