[package]
name = "agave-bls-cert-verify"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
description = "The BLS cert verify logic shared between sigverify and block marker consumption"
readme = "../README.md"
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[[bench]]
harness = false
name = "cert_verify"

[dependencies]
agave-votor-messages = { workspace = true }
bitvec = { workspace = true }
qualifier_attr = { workspace = true }
rayon = { workspace = true }
solana-bls-signatures = { workspace = true, features = ["parallel"] }
solana-signer-store = { workspace = true }
thiserror = { workspace = true }
wincode = { workspace = true }

[dev-dependencies]
agave-bls-cert-verify = { path = ".", features = ["agave-unstable-api", "dev-context-only-utils"] }
criterion = { workspace = true }
rand = { workspace = true }
solana-hash = { workspace = true }

[features]
agave-unstable-api = []
dev-context-only-utils = ["agave-votor-messages/dev-context-only-utils"]

[lints]
workspace = true
