[package]
name = "solana-program-binaries"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
description = "Prebuilt SPL and Core BPF programs"
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[dependencies]
bincode = { workspace = true }
solana-account = { workspace = true }
solana-loader-v3-interface = { workspace = true, features = ["bincode", "serde"] }
solana-pubkey = { workspace = true }
solana-rent = { workspace = true }
solana-sdk-ids = { workspace = true }
spl-generic-token = { workspace = true }

[features]
agave-unstable-api = []

[lints]
workspace = true
