[package]
name = "solana-pubkey"
description = "Solana account addresses"
documentation = "https://docs.rs/solana-pubkey"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
arbitrary = { workspace = true, features = ["derive"], optional = true }
borsh = { workspace = true, optional = true }
borsh0-10 = { package = "borsh", version = "0.10.3", optional = true }
bs58 = { workspace = true }
bytemuck = { workspace = true }
bytemuck_derive = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
solana-atomic-u64 = { workspace = true }
solana-decode-error = { workspace = true }
solana-define-syscall = { workspace = true }
solana-sanitize = { workspace = true }
thiserror = { workspace = true }

[target.'cfg(target_os = "solana")'.dependencies]
solana-hasher = { workspace = true }

[target.'cfg(not(target_os = "solana"))'.dependencies]
curve25519-dalek = { workspace = true, optional = true }
rand = { workspace = true }
solana-hasher = { workspace = true, optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { workspace = true, features = ["js", "wasm-bindgen"] }
js-sys = { workspace = true }
wasm-bindgen = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
arbitrary = { workspace = true, features = ["derive"] }
solana-program = { workspace = true, features = ["borsh"] }
solana-pubkey = { path = ".", features = ["borsh", "curve25519"] }

[features]
borsh = ["dep:borsh", "dep:borsh0-10"]
curve25519 = ["dep:curve25519-dalek", "sha2"]
dev-context-only-utils = ["dep:arbitrary"]
serde = ["dep:serde", "dep:serde_derive"]
sha2 = ["dep:solana-hasher", "solana-hasher/sha2"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
