[package]
name = "agave-banking-stage-ingress-types"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
description = "Agave banking stage ingress types"
documentation = "https://docs.rs/agave-banking-stage-ingress-types"
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[dependencies]
crossbeam-channel = { workspace = true }
solana-perf = { workspace = true }
wincode = { workspace = true, optional = true }

[features]
agave-unstable-api = []
dev-context-only-utils = ["dep:wincode"]

[lints]
workspace = true
