[package]
name = "solana-sbf-rust-poseidon"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = "Solana SBF test program written in Rust"
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[lib]
crate-type = ["cdylib"]

[dependencies]
solana-msg = { workspace = true }
solana-poseidon = { workspace = true }
solana-program-entrypoint = { workspace = true }

[lints]
workspace = true
