[package]
name = "agave-votor-messages"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
description = { workspace = true }
documentation = "https://docs.rs/agave-votor-messages"
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[dependencies]
agave-feature-set = { workspace = true }
bitvec = { workspace = true }
crossbeam-channel = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
smallvec = { workspace = true }
solana-address = { workspace = true, features = ["curve25519"] }
solana-bls-signatures = {
  workspace = true,
  features = [
    "bytemuck",
    "solana-signer-derive",
  ]
}
solana-clock = { workspace = true }
solana-epoch-schedule = { workspace = true }
solana-frozen-abi = {
  workspace = true,
  features = [
    "frozen-abi",
  ],
  optional = true
}
solana-frozen-abi-macro = {
  workspace = true,
  features = [
    "frozen-abi",
  ],
  optional = true
}
solana-hash = { workspace = true, features = ["atomic", "copy", "decode", "serde", "wincode"] }
solana-leader-schedule = { workspace = true }
solana-pubkey = { workspace = true }
solana-short-vec = { workspace = true, features = ["wincode"] }
solana-signer-store = { workspace = true }
thiserror = { workspace = true }
wincode = { workspace = true }

[features]
agave-unstable-api = []
dev-context-only-utils = []
frozen-abi = [
  "dep:solana-frozen-abi",
  "dep:solana-frozen-abi-macro",
  "solana-bls-signatures/frozen-abi",
  "solana-hash/frozen-abi",
]

[lints]
workspace = true
