[package]
name = "solana-zk-token-proof-program"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
description = "Solana Zk Token Proof Program"
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[dependencies]
solana-program-runtime = { workspace = true }

[features]
agave-unstable-api = []

[lints]
workspace = true
