[package]
name = "agave-fs"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
description = "Agave file system utils"
documentation = "https://docs.rs/agave-fs"
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[lib]
crate-type = ["lib"]
name = "agave_fs"

[dependencies]
libc = { workspace = true }
log = { workspace = true }
slab = { workspace = true }
smallvec = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
tempfile = { workspace = true }
test-case = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
agave-io-uring = { workspace = true }
io-uring = { workspace = true }
tempfile = { workspace = true }

[features]
agave-unstable-api = []

[lints]
workspace = true
