[package]
name = "solana-decode-error"
description = "Solana DecodeError Trait. Obsolete."
documentation = "https://docs.rs/solana-decode-error"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
