[package]
name = "solana-poh-bench"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
documentation = "https://docs.rs/solana-poh-bench"
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
agave-logger = { workspace = true }
clap = { version = "3.1.5", default-features = false, features = ["cargo", "std", "suggestions"] }
num_cpus = { workspace = true }
rayon = { workspace = true }
solana-entry = { workspace = true }
solana-measure = { workspace = true }
solana-sha256-hasher = { workspace = true }
solana-version = { workspace = true }

[features]
agave-unstable-api = []

[lints]
workspace = true
