[package]
name = "solana-acccount"
description = "Solana Account type"
documentation = "https://docs.rs/solana-account"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
qualifier_attr = { workspace = true, optional = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_derive = { workspace = true }
solana-program = { workspace = true }

[features]
dev-context-only-utils = ["dep:qualifier_attr"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
