[package]
name = "rbpf-cli"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
description = "Decommissioned CLI to test and analyze SBF programs"
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
keywords = ["JIT", "SBF", "interpreter"]
publish = false

[dependencies]

[features]
agave-unstable-api = []

[lints]
workspace = true
