[package]
name = "solana-bloom"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
description = "Solana bloom filter"
documentation = "https://docs.rs/solana-bloom"
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[lib]
crate-type = ["lib"]
name = "solana_bloom"

[[bench]]
harness = false
name = "bloom"

[dependencies]
bv = { workspace = true }
fnv = { workspace = true }
rand = { workspace = true }
solana-frozen-abi = {
  workspace = true,
  features = [
    "frozen-abi",
  ],
  optional = true
}
solana-frozen-abi-macro = {
  workspace = true,
  features = [
    "frozen-abi",
  ],
  optional = true
}
solana-sanitize = { workspace = true }
solana-time-utils = { workspace = true }
wincode = { workspace = true, features = ["bv"] }

[dev-dependencies]
bencher = { workspace = true }
rayon = { workspace = true }
solana-bloom = { path = ".", features = ["agave-unstable-api", "dev-context-only-utils"] }
solana-hash = { workspace = true, features = ["atomic", "wincode"] }
solana-sha256-hasher = { workspace = true, features = ["sha2"] }
solana-signature = { workspace = true, features = ["std"] }

[features]
agave-unstable-api = []
dev-context-only-utils = []
frozen-abi = [
  "dep:solana-frozen-abi",
  "dep:solana-frozen-abi-macro",
  "solana-hash/frozen-abi",
]

[lints]
workspace = true
