[package]
name = "agave-io-uring"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
description = "Agave io_uring wrapper"
documentation = "https://docs.rs/agave-io-uring"
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[dependencies]
libc = { workspace = true }
log = { workspace = true }
slab = { workspace = true }
smallvec = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
io-uring = { workspace = true }

[features]
agave-unstable-api = []

[lints]
workspace = true
