[package]
name = "solana-transaction"
description = "Solana Transaction"
documentation = "https://docs.rs/solana-transaction"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
solana-program = { workspace = true }
solana-sdk = { workspace = true }
