[package]
name = "solana-sbf-rust-alt-bn128"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = "Solana BPF test program written in Rust"
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[lib]
crate-type = ["cdylib"]

[dependencies]
solana-bn254 = { workspace = true }
solana-msg = { workspace = true }
solana-program-entrypoint = { workspace = true }

[lints]
workspace = true
