[package]
name = "agave-scheduling-utils"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
description = "Common utilities for building Agave scheduler implementations"
documentation = "https://docs.rs/agave-scheduling-utils"
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[dependencies]
agave-feature-set = { workspace = true }
agave-scheduler-bindings = { workspace = true }
agave-transaction-view = { workspace = true }
ahash = { workspace = true }
rts-alloc = { workspace = true }
shaq = { workspace = true }
slotmap = { workspace = true }
solana-fee = { workspace = true, features = ["agave-unstable-api"] }
solana-pubkey = { workspace = true }
solana-runtime-transaction = { workspace = true }
solana-transaction = { workspace = true, features = ["serde"], optional = true }
solana-transaction-error = { workspace = true }
thiserror = { workspace = true }
wincode = { workspace = true, optional = true }

[dev-dependencies]
solana-pubkey = { workspace = true, features = ["rand"] }
tempfile = { workspace = true }

[target."cfg(unix)".dependencies]
libc = { workspace = true }
nix = { workspace = true, features = ["socket", "uio"] }

[target."cfg(unix)".dev-dependencies]
agave-scheduler-bindings = { workspace = true }

[features]
agave-unstable-api = []
dev-context-only-utils = ["dep:solana-transaction", "dep:wincode"]

[lints]
workspace = true
