[package]
name = "agave-store-histogram"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
description = "Tool to calculate account storage histogram"
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
publish = false

[dependencies]
clap = { workspace = true }
solana-version = { workspace = true }

[features]
agave-unstable-api = []
dev-context-only-utils = []

[lints]
workspace = true
