[package]
name = "solana-sbf-rust-mem-dep"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[lib]
crate-type = ["lib"]

[dependencies]

[lints]
workspace = true
