[package]
name = "solana-sysvar-id"
description = "Definition for the sysvar id trait and associated macros."
documentation = "https://docs.rs/solana-sysvar-id"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
solana-program-error = { workspace = true }
solana-pubkey = { workspace = true, default-features = false }

[dev-dependencies]
solana-program-entrypoint = { workspace = true }
static_assertions = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[lints]
workspace = true
