[package]
name = "solana-svm-timings"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
description = "Solana Execution Timings"
documentation = "https://docs.rs/solana-svm-timings"
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[dependencies]
eager = { workspace = true }
enum-iterator = { workspace = true }
solana-pubkey = { workspace = true }

[dev-dependencies]
solana-pubkey = { workspace = true, features = ["rand"] }

[features]
agave-unstable-api = []

[lints]
workspace = true
