[package]
name = "solana-program-core"
description = "Solana Program Core SDK"
documentation = "https://docs.rs/solana-program-core"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
rust-version = "1.75.0"                               # solana platform-tools rust version

[dependencies]
bincode = { workspace = true, optional = true }
blake3 = { workspace = true, features = ["digest", "traits-preview"], optional = true }
borsh = { workspace = true, optional = true }
borsh0-10 = { package = "borsh", version = "0.10.3", optional = true }
bs58 = { workspace = true }
bv = { workspace = true, optional = true }
bytemuck = { workspace = true, optional = true }
bytemuck_derive = { workspace = true, optional = true }
five8_const = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
memoffset = { workspace = true }
num-traits = { workspace = true, features = ["i128"] }
qualifier_attr = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_bytes = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
sha2 = { workspace = true, optional = true }
sha3 = { workspace = true, optional = true }
solana-atomic-u64 = { workspace = true }
solana-decode-error = { workspace = true }
solana-frozen-abi = { workspace = true, optional = true }
solana-frozen-abi-macro = { workspace = true, optional = true }
solana-msg = { workspace = true }
solana-program-memory = { workspace = true }
solana-sanitize = { workspace = true }
solana-short-vec = { workspace = true, optional = true }

# This is currently needed to build on-chain programs reliably.
# Borsh 0.10 may pull in hashbrown 0.13, which uses ahash 0.8, which uses
# getrandom 0.2 underneath. This explicit dependency allows for no-std if cargo
# upgrades Borsh's dependency to hashbrown 0.13.
# Remove this once borsh 0.11 or 1.0 is released, which correctly declares the
# hashbrown dependency as optional.
[target.'cfg(target_os = "solana")'.dependencies]
getrandom = { workspace = true, features = ["custom"], optional = true }
solana-define-syscall = { workspace = true }

[target.'cfg(not(target_os = "solana"))'.dependencies]
arbitrary = { workspace = true, features = ["derive"], optional = true }
base64 = { workspace = true, features = ["alloc", "std"], optional = true }
bitflags = { workspace = true }
curve25519-dalek = { workspace = true, optional = true }

[target.'cfg(not(target_os = "solana"))'.dev-dependencies]
arbitrary = { workspace = true, features = ["derive"] }
rand = { workspace = true }
solana-logger = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = { workspace = true }
console_log = { workspace = true }
getrandom = { workspace = true, features = ["js", "wasm-bindgen"] }
js-sys = { workspace = true }
wasm-bindgen = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
itertools = { workspace = true }
serde_json = { workspace = true }
serial_test = { workspace = true }
solana-program-core = { path = ".", features = ["dev-context-only-utils"] }
static_assertions = { workspace = true }

[build-dependencies]
rustc_version = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
base64 = ["dep:base64"]
bincode = ["dep:bincode", "serde"]
blake3 = ["dep:blake3"]
borsh = ["dep:borsh", "dep:borsh0-10", "dep:getrandom"]
bv = ["dep:bv"]
bytemuck = ["dep:bytemuck", "dep:bytemuck_derive"]
curve25519 = ["dep:curve25519-dalek"]
dev-context-only-utils = [
    "dep:arbitrary",
    "dep:qualifier_attr",
    "base64",
    "bincode",
    "blake3",
    "borsh",
    "bv",
    "bytemuck",
    "curve25519",
    "serde",
    "sha2",
    "sha3"
]
frozen-abi = [
    "dep:solana-frozen-abi",
    "dep:solana-frozen-abi-macro",
    "solana-short-vec/frozen-abi",
]
serde = [
    "dep:serde",
    "dep:serde_bytes",
    "dep:serde_derive",
    "dep:solana-short-vec",
    "bv/serde"
]
sha2 = ["dep:sha2"]
sha3 = ["dep:sha3"]
