[package]
name = "solana-system-instruction"
description = "Instructions and constructors for the Solana system program."
documentation = "https://docs.rs/solana-system-instruction"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
num-derive = { workspace = true }
num-traits = { workspace = true }
solana-decode-error = { workspace = true }
solana-pubkey = { workspace = true, default-features = false }
solana-frozen-abi = { workspace = true, optional = true }
solana-frozen-abi-macro = { workspace = true, optional = true }

[dev-dependencies]
solana-instruction = { workspace = true }
solana-program = { path = "../program", default-features = false }
static_assertions = { workspace = true }

[features]
default = ["std"]
frozen-abi = [
    "dep:solana-frozen-abi",
    "dep:solana-frozen-abi-macro",
    "std"
]
std = []

[lints]
workspace = true
