[package]
name = "solana-instruction"
description = "Types for directing the execution of Solana programs."
documentation = "https://docs.rs/solana-instruction"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true, optional = true }
borsh = { workspace = true, optional = true }
num-traits = { workspace = true }
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
solana-frozen-abi = { workspace = true, optional = true }
solana-frozen-abi-macro = { workspace = true, optional = true }
solana-pubkey = { workspace = true, default-features = false, features = [
    "serde",
] }
solana-sanitize = { workspace = true }
solana-short-vec = { workspace = true, optional = true }

[target.'cfg(target_os = "solana")'.dependencies]
solana-define-syscall = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { workspace = true, features = ["js", "wasm-bindgen"] }
js-sys = { workspace = true }
wasm-bindgen = { workspace = true }

[dev-dependencies]
solana-instruction = { path = ".", features = ["borsh", "dev-context-only-utils"] }

[build-dependencies]
rustc_version = { workspace = true }

[features]
bincode = ["dep:bincode", "dep:serde"]
borsh = ["dep:borsh"]
dev-context-only-utils = [] # unused but CI fails without this.
frozen-abi = ["dep:solana-frozen-abi", "dep:solana-frozen-abi-macro"]
serde = ["dep:serde", "dep:serde_derive", "dep:solana-short-vec"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
