[package]
name = "solana-program-option"
description = "A C representation of Rust's Option"
documentation = "https://docs.rs/solana-program-option"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dev-dependencies]
# circular dev deps need to be path deps for `cargo publish` to be happy
solana-program = { path = "../program" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
