[workspace.package]
version = "2.3.0"
description = "Solana SBF test program written in Rust"
authors = ["Anza Maintainers <maintainers@anza.xyz>"]
repository = "https://github.com/anza-xyz/agave"
homepage = "https://anza.xyz"
license = "Apache-2.0"
edition = "2021"

[workspace.lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = [
    'cfg(target_os, values("solana"))',
    'cfg(feature, values("custom-panic", "custom-heap"))'
]

[workspace.dependencies]
agave-feature-set = { path = "../../feature-set", version = "=2.3.0" }
agave-reserved-account-keys = { path = "../../reserved-account-keys", version = "=2.3.0" }
array-bytes = "=1.4.1"
bincode = { version = "1.1.4", default-features = false }
blake3 = "1.0.0"
borsh = "1.5.1"
byteorder = "1.3.2"
elf = "0.0.10"
getrandom = "0.2.10"
itertools = "0.10.1"
libsecp256k1 = { version = "0.7.0", default-features = false }
log = "0.4.11"
miow = "0.3.6"
net2 = "0.2.37"
num-derive = "0.4.2"
num-traits = "0.2"
rand = "0.8"
serde = "1.0.112"                                                                             # must match the serde_derive version, see https://github.com/serde-rs/serde/issues/2584#issuecomment-1685252251
serde_derive = "1.0.112"                                                                      # must match the serde version, see https://github.com/serde-rs/serde/issues/2584#issuecomment-1685252251
serde_json = "1.0.56"
solana-account-decoder = { path = "../../account-decoder", version = "=2.3.0" }
solana-accounts-db = { path = "../../accounts-db", version = "=2.3.0" }
solana-bn254 = "=2.2.1"
solana-bpf-loader-program = { path = "../bpf_loader", version = "=2.3.0" }
solana-cli-output = { path = "../../cli-output", version = "=2.3.0" }
solana-compute-budget = { path = "../../compute-budget", version = "=2.3.0" }
solana-compute-budget-instruction = { path = "../../compute-budget-instruction", version = "=2.3.0" }
solana-curve25519 = { path = "../../curves/curve25519", version = "=2.3.0" }
solana-decode-error = "=2.2.1"
solana-fee = { path = "../../fee", version = "=2.3.0" }
solana-ledger = { path = "../../ledger", version = "=2.3.0" }
solana-log-collector = { path = "../../log-collector", version = "=2.3.0" }
solana-logger = "=2.3.1"
solana-measure = { path = "../../measure", version = "=2.3.0" }
solana-poseidon = { path = "../../poseidon/", version = "=2.3.0" }
solana-program = "=2.2.1"
solana-program-runtime = { path = "../../program-runtime", version = "=2.3.0" }
solana-runtime = { path = "../../runtime", version = "=2.3.0" }
solana-runtime-transaction = { path = "../../runtime-transaction", version = "=2.3.0" }
solana-sbf-rust-128bit-dep = { path = "rust/128bit_dep", version = "=2.3.0" }
solana-sbf-rust-invoke-dep = { path = "rust/invoke_dep", version = "=2.3.0" }
solana-sbf-rust-invoked-dep = { path = "rust/invoked_dep", version = "=2.3.0" }
solana-sbf-rust-many-args-dep = { path = "rust/many_args_dep", version = "=2.3.0" }
solana-sbf-rust-mem-dep = { path = "rust/mem_dep", version = "=2.3.0" }
solana-sbf-rust-param-passing-dep = { path = "rust/param_passing_dep", version = "=2.3.0" }
solana-sbf-rust-realloc-dep = { path = "rust/realloc_dep", version = "=2.3.0" }
solana-sbf-rust-realloc-invoke-dep = { path = "rust/realloc_invoke_dep", version = "=2.3.0" }
solana-sdk = "=2.2.1"
solana-sbpf = "=0.11.0"
solana-secp256k1-recover = "=2.2.1"
solana-svm = { path = "../../svm", version = "=2.3.0" }
solana-svm-callback = { path = "../../svm-callback", version = "=2.3.0" }
solana-svm-transaction = { path = "../../svm-transaction", version = "=2.3.0" }
solana-timings = { path = "../../timings", version = "=2.3.0" }
solana-transaction-context = { path = "../../transaction-context", version = "=2.3.0" }
solana-transaction-status = { path = "../../transaction-status", version = "=2.3.0" }
solana-type-overrides = { path = "../../type-overrides", version = "=2.3.0" }
solana-vote = { path = "../../vote", version = "=2.3.0" }
solana-vote-program = { path = "../../programs/vote", version = "=2.3.0" }
agave-validator = { path = "../../validator", version = "=2.3.0" }
solana-zk-sdk = "=2.2.1"
thiserror = "1.0"

[package]
name = "solana-sbf-programs"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/solana"
readme = "README.md"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[profile.release]
# The test programs are build in release mode
# Minimize their file size so that they fit into the account size limit
strip = true

[features]
sbf_c = []
sbf_rust = []
sbf_sanity_list = []
dummy-for-ci-check = ["sbf_c", "sbf_rust", "sbf_sanity_list"]
# This was needed for ci
frozen-abi = []

[dev-dependencies]
agave-feature-set = { workspace = true }
agave-reserved-account-keys = { workspace = true }
agave-validator = { workspace = true }
bincode = { workspace = true }
borsh = { workspace = true }
byteorder = { workspace = true }
elf = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
miow = { workspace = true }
net2 = { workspace = true }
solana-account-decoder = { workspace = true }
solana-accounts-db = { workspace = true }
solana-bpf-loader-program = { workspace = true }
solana-cli-output = { workspace = true }
solana-compute-budget = { workspace = true }
solana-compute-budget-instruction = { workspace = true, features = [
    "dev-context-only-utils",
] }
solana-fee = { workspace = true }
solana-ledger = { workspace = true }
solana-log-collector = { workspace = true }
solana-logger = { workspace = true }
solana-measure = { workspace = true }
solana-program = { workspace = true }
solana-program-runtime = { workspace = true }
solana-runtime = { workspace = true, features = ["dev-context-only-utils"] }
solana-runtime-transaction = { workspace = true, features = [
    "dev-context-only-utils",
] }
solana-sbf-rust-invoke-dep = { workspace = true }
solana-sbf-rust-realloc-dep = { workspace = true }
solana-sbf-rust-realloc-invoke-dep = { workspace = true }
solana-sbpf = { workspace = true }
solana-sdk = { workspace = true, features = ["dev-context-only-utils"] }
solana-svm = { workspace = true }
solana-svm-callback = { workspace = true }
solana-svm-transaction = { workspace = true }
solana-timings = { workspace = true }
solana-transaction-context = { workspace = true, features = ["dev-context-only-utils"] }
solana-transaction-status = { workspace = true }
solana-type-overrides = { workspace = true }
solana-vote = { workspace = true }
solana-vote-program = { workspace = true }

[[bench]]
name = "bpf_loader"

[workspace]
members = [
    "rust/128bit",
    "rust/128bit_dep",
    "rust/account_mem",
    "rust/account_mem_deprecated",
    "rust/alloc",
    "rust/alt_bn128",
    "rust/alt_bn128_compression",
    "rust/big_mod_exp",
    "rust/call_args",
    "rust/call_depth",
    "rust/caller_access",
    "rust/curve25519",
    "rust/custom_heap",
    "rust/dep_crate",
    "rust/deprecated_loader",
    "rust/divide_by_zero",
    "rust/dup_accounts",
    "rust/error_handling",
    "rust/external_spend",
    "rust/get_minimum_delegation",
    "rust/inner_instruction_alignment_check",
    "rust/instruction_introspection",
    "rust/invoke",
    "rust/invoke_and_error",
    "rust/invoke_and_ok",
    "rust/invoke_and_return",
    "rust/invoked",
    "rust/iter",
    "rust/log_data",
    "rust/many_args",
    "rust/many_args_dep",
    "rust/mem",
    "rust/mem_dep",
    "rust/membuiltins",
    "rust/noop",
    "rust/panic",
    "rust/param_passing",
    "rust/param_passing_dep",
    "rust/poseidon",
    "rust/rand",
    "rust/realloc",
    "rust/realloc_invoke",
    "rust/remaining_compute_units",
    "rust/ro_account_modify",
    "rust/ro_modify",
    "rust/sanity",
    "rust/secp256k1_recover",
    "rust/sha",
    "rust/sibling_inner_instructions",
    "rust/sibling_instructions",
    "rust/simulation",
    "rust/spoof1",
    "rust/spoof1_system",
    "rust/syscall-get-epoch-stake",
    "rust/sysvar",
    "rust/upgradeable",
    "rust/upgraded",
]

[patch.crates-io]
# We include the following crates as our dependencies from crates.io:
#
#  * spl-associated-token-account
#  * spl-instruction-padding
#  * spl-memo
#  * spl-pod
#  * spl-token
#  * spl-token-2022
#  * spl-token-metadata-interface
#
# They are included indirectly, for example, `account-decoder` depends on
#
#     solana-sdk = { workspace = true }
#
# and that is specified as
#
#     spl-token = "=3.5.0"
#
# in `../../Cargo.toml`.
#
# `spl-token`, in turn, depends on `solana-program`, which we explicitly specify
# above as a local path dependency:
#
#     solana-program = { path = "../../sdk/program", version = "=1.16.0" }
#
# Unfortunately, Cargo will try to resolve the `spl-token` `solana-program`
# dependency only using what is available on crates.io.  Crates.io normally
# contains a previous version of these crates, and we end up with two versions
# of `solana-program` and `solana-zk-token-sdk` and all of their dependencies in
# our build tree.
#
# If you are developing downstream using non-crates-io solana-program (local or
# forked repo, or from github rev, eg), duplicate the following patch statements
# in your Cargo.toml. If you still hit duplicate-type errors with the patch
# statements in place, run `cargo update -p solana-program` and/or `cargo update
# -p solana-zk-token-sdk` to remove extraneous versions from your Cargo.lock
# file.
#
# There is a similar override in `../../Cargo.toml`.  Please keep both comments
# and the overrides in sync.
solana-curve25519 = { path = "../../curves/curve25519" }
solana-zk-sdk = { path = "../../zk-sdk" }
# The following entries are auto-generated by ../../../solana-sdk/scripts/patch-crates-no-header.sh
solana-account = { path = "/home/sol/src/solana-sdk/account" }
solana-account-info = { path = "/home/sol/src/solana-sdk/account-info" }
solana-address-lookup-table-interface = { path = "/home/sol/src/solana-sdk/address-lookup-table-interface" }
solana-atomic-u64 = { path = "/home/sol/src/solana-sdk/atomic-u64" }
solana-big-mod-exp = { path = "/home/sol/src/solana-sdk/big-mod-exp" }
solana-bincode = { path = "/home/sol/src/solana-sdk/bincode" }
solana-blake3-hasher = { path = "/home/sol/src/solana-sdk/blake3-hasher" }
solana-bn254 = { path = "/home/sol/src/solana-sdk/bn254" }
solana-borsh = { path = "/home/sol/src/solana-sdk/borsh" }
solana-client-traits = { path = "/home/sol/src/solana-sdk/client-traits" }
solana-clock = { path = "/home/sol/src/solana-sdk/clock" }
solana-cluster-type = { path = "/home/sol/src/solana-sdk/cluster-type" }
solana-commitment-config = { path = "/home/sol/src/solana-sdk/commitment-config" }
solana-compute-budget-interface = { path = "/home/sol/src/solana-sdk/compute-budget-interface" }
solana-cpi = { path = "/home/sol/src/solana-sdk/cpi" }
solana-decode-error = { path = "/home/sol/src/solana-sdk/decode-error" }
solana-define-syscall = { path = "/home/sol/src/solana-sdk/define-syscall" }
solana-derivation-path = { path = "/home/sol/src/solana-sdk/derivation-path" }
solana-ed25519-program = { path = "/home/sol/src/solana-sdk/ed25519-program" }
solana-epoch-info = { path = "/home/sol/src/solana-sdk/epoch-info" }
solana-epoch-rewards = { path = "/home/sol/src/solana-sdk/epoch-rewards" }
solana-epoch-rewards-hasher = { path = "/home/sol/src/solana-sdk/epoch-rewards-hasher" }
solana-epoch-schedule = { path = "/home/sol/src/solana-sdk/epoch-schedule" }
solana-example-mocks = { path = "/home/sol/src/solana-sdk/example-mocks" }
solana-feature-gate-interface = { path = "/home/sol/src/solana-sdk/feature-gate-interface" }
solana-feature-set = { path = "/home/sol/src/solana-sdk/feature-set" }
solana-fee-calculator = { path = "/home/sol/src/solana-sdk/fee-calculator" }
solana-fee-structure = { path = "/home/sol/src/solana-sdk/fee-structure" }
solana-file-download = { path = "/home/sol/src/solana-sdk/file-download" }
solana-frozen-abi = { path = "/home/sol/src/solana-sdk/frozen-abi" }
solana-frozen-abi-macro = { path = "/home/sol/src/solana-sdk/frozen-abi-macro" }
solana-genesis-config = { path = "/home/sol/src/solana-sdk/genesis-config" }
solana-hard-forks = { path = "/home/sol/src/solana-sdk/hard-forks" }
solana-hash = { path = "/home/sol/src/solana-sdk/hash" }
solana-inflation = { path = "/home/sol/src/solana-sdk/inflation" }
solana-instruction = { path = "/home/sol/src/solana-sdk/instruction" }
solana-instructions-sysvar = { path = "/home/sol/src/solana-sdk/instructions-sysvar" }
solana-keccak-hasher = { path = "/home/sol/src/solana-sdk/keccak-hasher" }
solana-keypair = { path = "/home/sol/src/solana-sdk/keypair" }
solana-last-restart-slot = { path = "/home/sol/src/solana-sdk/last-restart-slot" }
solana-loader-v2-interface = { path = "/home/sol/src/solana-sdk/loader-v2-interface" }
solana-loader-v3-interface = { path = "/home/sol/src/solana-sdk/loader-v3-interface" }
solana-loader-v4-interface = { path = "/home/sol/src/solana-sdk/loader-v4-interface" }
solana-logger = { path = "/home/sol/src/solana-sdk/logger" }
solana-message = { path = "/home/sol/src/solana-sdk/message" }
solana-msg = { path = "/home/sol/src/solana-sdk/msg" }
solana-native-token = { path = "/home/sol/src/solana-sdk/native-token" }
solana-nonce = { path = "/home/sol/src/solana-sdk/nonce" }
solana-nonce-account = { path = "/home/sol/src/solana-sdk/nonce-account" }
solana-offchain-message = { path = "/home/sol/src/solana-sdk/offchain-message" }
solana-package-metadata = { path = "/home/sol/src/solana-sdk/package-metadata" }
solana-package-metadata-macro = { path = "/home/sol/src/solana-sdk/package-metadata-macro" }
solana-packet = { path = "/home/sol/src/solana-sdk/packet" }
solana-poh-config = { path = "/home/sol/src/solana-sdk/poh-config" }
solana-precompile-error = { path = "/home/sol/src/solana-sdk/precompile-error" }
solana-precompiles = { path = "/home/sol/src/solana-sdk/precompiles" }
solana-presigner = { path = "/home/sol/src/solana-sdk/presigner" }
solana-program = { path = "/home/sol/src/solana-sdk/program" }
solana-program-entrypoint = { path = "/home/sol/src/solana-sdk/program-entrypoint" }
solana-program-error = { path = "/home/sol/src/solana-sdk/program-error" }
solana-program-memory = { path = "/home/sol/src/solana-sdk/program-memory" }
solana-program-option = { path = "/home/sol/src/solana-sdk/program-option" }
solana-program-pack = { path = "/home/sol/src/solana-sdk/program-pack" }
solana-pubkey = { path = "/home/sol/src/solana-sdk/pubkey" }
solana-quic-definitions = { path = "/home/sol/src/solana-sdk/quic-definitions" }
solana-rent = { path = "/home/sol/src/solana-sdk/rent" }
solana-rent-collector = { path = "/home/sol/src/solana-sdk/rent-collector" }
solana-rent-debits = { path = "/home/sol/src/solana-sdk/rent-debits" }
solana-reserved-account-keys = { path = "/home/sol/src/solana-sdk/reserved-account-keys" }
solana-reward-info = { path = "/home/sol/src/solana-sdk/reward-info" }
solana-sanitize = { path = "/home/sol/src/solana-sdk/sanitize" }
solana-sdk = { path = "/home/sol/src/solana-sdk/sdk" }
solana-sdk-ids = { path = "/home/sol/src/solana-sdk/sdk-ids" }
solana-sdk-macro = { path = "/home/sol/src/solana-sdk/sdk-macro" }
solana-secp256k1-program = { path = "/home/sol/src/solana-sdk/secp256k1-program" }
solana-secp256k1-recover = { path = "/home/sol/src/solana-sdk/secp256k1-recover" }
solana-secp256r1-program = { path = "/home/sol/src/solana-sdk/secp256r1-program" }
solana-seed-derivable = { path = "/home/sol/src/solana-sdk/seed-derivable" }
solana-seed-phrase = { path = "/home/sol/src/solana-sdk/seed-phrase" }
solana-serde = { path = "/home/sol/src/solana-sdk/serde" }
solana-serde-varint = { path = "/home/sol/src/solana-sdk/serde-varint" }
solana-serialize-utils = { path = "/home/sol/src/solana-sdk/serialize-utils" }
solana-sha256-hasher = { path = "/home/sol/src/solana-sdk/sha256-hasher" }
solana-short-vec = { path = "/home/sol/src/solana-sdk/short-vec" }
solana-shred-version = { path = "/home/sol/src/solana-sdk/shred-version" }
solana-signature = { path = "/home/sol/src/solana-sdk/signature" }
solana-signer = { path = "/home/sol/src/solana-sdk/signer" }
solana-slot-hashes = { path = "/home/sol/src/solana-sdk/slot-hashes" }
solana-slot-history = { path = "/home/sol/src/solana-sdk/slot-history" }
solana-stable-layout = { path = "/home/sol/src/solana-sdk/stable-layout" }
solana-system-transaction = { path = "/home/sol/src/solana-sdk/system-transaction" }
solana-sysvar = { path = "/home/sol/src/solana-sdk/sysvar" }
solana-sysvar-id = { path = "/home/sol/src/solana-sdk/sysvar-id" }
solana-time-utils = { path = "/home/sol/src/solana-sdk/time-utils" }
solana-transaction = { path = "/home/sol/src/solana-sdk/transaction" }
solana-transaction-context = { path = "/home/sol/src/solana-sdk/transaction-context" }
solana-transaction-error = { path = "/home/sol/src/solana-sdk/transaction-error" }
solana-validator-exit = { path = "/home/sol/src/solana-sdk/validator-exit" }
solana-vote-interface = { path = "/home/sol/src/solana-sdk/vote-interface" }
