[package]
name = "solana-zk-elgamal-proof-program"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
description = "Solana Zk ElGamal Proof Program"
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[[bench]]
harness = false
name = "verify_proofs"

[dependencies]
bytemuck = { workspace = true }
solana-instruction = { workspace = true, features = ["std"] }
solana-program-runtime = { workspace = true }
solana-sdk-ids = { workspace = true }
solana-svm-log-collector = { workspace = true }
solana-zk-elgamal-proof-interface = { workspace = true }
solana-zk-sdk = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[features]
agave-unstable-api = []

[lints]
workspace = true
