[package]
name = "agave-math-utils"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
description = "Math utilities for Agave"
readme = "../README.md"
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[dependencies]
num-traits = { workspace = true }

[dev-dependencies]
agave-math-utils = { path = ".", features = ["agave-unstable-api"] }
rand = { workspace = true }
test-case = { workspace = true }

[features]
agave-unstable-api = []

[lints]
workspace = true
