[package]
name = "solana-svm-fuzz-harness"
description = "Solana SVM fuzzing harness"
documentation = "https://docs.rs/solana-svm-fuzz-harness"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
lazy_static = { workspace = true }
prost = { workspace = true }
solana-account = { workspace = true }
solana-address-lookup-table-program = { workspace = true }
solana-bpf-loader-program = { workspace = true }
solana-clock = { workspace = true }
solana-compute-budget = { workspace = true }
solana-compute-budget-program = { workspace = true }
solana-config-program = { workspace = true }
solana-epoch-schedule = { workspace = true }
solana-feature-set = { workspace = true }
solana-hash = { workspace = true }
solana-instruction = { workspace = true }
solana-log-collector = { workspace = true }
solana-program-runtime = { workspace = true }
solana-pubkey = { workspace = true }
solana-rent = { workspace = true }
# Remove me when `solana_rent_collector` is split out from SDK.
solana-sdk = { workspace = true }
solana-sdk-ids = { workspace = true }
solana-stable-layout = { workspace = true }
solana-stake-program = { workspace = true }
solana-timings = { workspace = true }
solana-system-program = { workspace = true }
solana-vote-program = { workspace = true }
solana-zk-elgamal-proof-program = { workspace = true }
solana-zk-token-proof-program = { workspace = true }
thiserror = { workspace = true }

[build-dependencies]
prost-build = { workspace = true }

[lints]
workspace = true
