[package]
name = "solana-svm-fuzz-harness"
description = "Solana SVM fuzzing harness"
documentation = "https://docs.rs/solana-svm-fuzz-harness"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
prost = { workspace = true }
thiserror = { workspace = true }

[build-dependencies]
prost-build = { workspace = true }

[lints]
workspace = true
