[package]
name = "solana-inner-instruction"
description = "Solana inner instruction types."
documentation = "https://docs.rs/solana-inner-instruction"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
solana-message = { workspace = true }

[features]
serde = ["dep:serde", "dep:serde_derive", "solana-message/serde"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]
