[package]
name = "solana-shred"
description = "Solana shred wire parser and serializer"
documentation = "https://docs.rs/solana-shred"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
dev-context-only-utils = ["dep:bs58"]

[dependencies]
bs58 = { workspace = true, features = ["alloc"], optional = true }
bytes = { workspace = true }
solana-clock = { workspace = true }
solana-hash = { workspace = true, features = ["decode", "wincode"] }
solana-keypair = { workspace = true }
solana-pubkey = { workspace = true }
solana-signature = { workspace = true, features = ["verify", "wincode"] }
solana-signer = { workspace = true }
static_assertions = { workspace = true }
thiserror = { workspace = true }
wincode = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
solana-shred = { path = ".", features = ["dev-context-only-utils"] }
test-case = { workspace = true }

[lints]
workspace = true
