use {
    agave_votor_messages::{
        certificate::Certificate, consensus_message::VoteMessage, vote::Vote,
        wire::VotePayloadToSign,
    },
    bitvec::vec::BitVec,
    solana_bls_signatures::{AsSignatureProjective, SignatureProjective},
    solana_runtime::bank::Bank,
    std::num::NonZero,
};

/// A batch of vote or cert being sent within the node.  They were either sig verified before being
/// sent or they were generated by the node itself so do not need to be sig verified.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SigVerifiedBatch {
    /// Batch of votes.
    Votes(Vec<VoteAggregate>),
    /// Batch of certs.
    Certificates(Vec<Certificate>),
}

impl SigVerifiedBatch {
    /// Returns the length of the batch
    pub fn len(&self) -> usize {
        match self {
            Self::Votes(aggregates) => aggregates.len(),
            Self::Certificates(certs) => certs.len(),
        }
    }

    /// Returns true if the batch is empty.
    pub fn is_empty(&self) -> bool {
        match self {
            Self::Votes(aggregates) => aggregates.is_empty(),
            Self::Certificates(certs) => certs.is_empty(),
        }
    }
}

/// A batch of identical votes that have been sigverified
///
/// NOTE: the fields should not be exposed outside of the crate so that users use approved paths to
/// build it to ensure signature verification takes place.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct VoteAggregate {
    /// The type of vote in the batch.
    pub(crate) vote: Vote,
    /// The aggregate signature of the votes in the batch.
    pub(crate) signature: SignatureProjective,
    /// The total stake in the batch.
    pub(crate) stake: NonZero<u64>,
    /// Ranks of the various validators whose votes are in the batch.
    pub(crate) ranks: BitVec<u8>,
}

impl VoteAggregate {
    /// Creates a sig verified vote batch from a VoteMessage.
    ///
    /// WARN: this is only public to enable handling already verified votes that are sent within
    /// the validator.  Think carefully before using this in production code.
    pub fn new_from_verified_vote(bank: &Bank, msg: VoteMessage) -> Self {
        // Since the `msg` is supposed to be verified, the unwraps below should be safe.
        let rank_map = bank
            .epoch_stakes_from_slot(msg.vote.slot())
            .unwrap()
            .bls_pubkey_to_rank_map();
        let stake = rank_map
            .get_pubkey_stake_entry(msg.rank as usize)
            .unwrap()
            .stake;
        let max_validators = rank_map.len();
        assert!((msg.rank as usize) < max_validators);
        let mut ranks = BitVec::repeat(false, max_validators);
        ranks.set(msg.rank as usize, true);
        Self {
            vote: msg.vote,
            signature: msg.signature.try_as_projective().unwrap(),
            stake,
            ranks,
        }
    }

    /// Creates a sig verified vote batch from a list of verified votes.
    ///
    /// WARN: this function should not be exposed outside of this crate.  This crate uses it after
    /// it has verified the votes.
    pub(crate) fn new_from_verified_votes(
        bank: &Bank,
        vote_payload_to_sign: VotePayloadToSign,
        ranks_iter: impl Iterator<Item = u16>,
        aggregate_signature: SignatureProjective,
    ) -> Option<Self> {
        let rank_map = bank
            .epoch_stakes_from_slot(vote_payload_to_sign.slot())?
            .bls_pubkey_to_rank_map();
        let max_validators = rank_map.len();
        let mut ranks = BitVec::repeat(false, max_validators);
        let mut total_stake = None;
        for rank in ranks_iter {
            if *ranks.get(rank as usize)? {
                continue;
            }
            let stake = rank_map.get_pubkey_stake_entry(rank as usize)?.stake;
            match total_stake {
                None => total_stake = Some(stake),
                Some(t) => total_stake = Some(t.saturating_add(stake.get())),
            }
            ranks.set(rank as usize, true);
        }
        let vote = Vote::from(vote_payload_to_sign);
        Some(Self {
            vote,
            signature: aggregate_signature,
            stake: total_stake?,
            ranks,
        })
    }

    pub fn vote(&self) -> &Vote {
        &self.vote
    }

    pub fn ranks(&self) -> &BitVec<u8> {
        &self.ranks
    }

    pub fn signature(&self) -> &SignatureProjective {
        &self.signature
    }

    pub fn stake(&self) -> NonZero<u64> {
        self.stake
    }

    /// Returns number of votes in the aggregate.
    pub fn num_votes(&self) -> usize {
        self.ranks.count_ones()
    }
}
