name: Cargo

on:
  workflow_dispatch:
    inputs:
      sha:
        description: "commit hash"
        required: true
      ref:
        description: "branch"
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.ref || github.event.inputs.sha }}
  cancel-in-progress: true

env:
  SHELL: /bin/bash
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  setup-status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          result-encoding: string
          retries: 3
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              context: "macos-clippy",
              description: "triggered by buildkite",
              sha: "${{ github.event.inputs.sha }}",
              state: "pending",
              target_url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            })

  clippy-stable:
    needs: setup-status
    strategy:
      matrix:
        os:
          - macos-latest-large
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: mozilla-actions/sccache-action@v0.0.3
        with:
          version: "v0.5.4"

      - shell: bash
        run: .github/scripts/cargo-clippy-before-script.sh ${{ runner.os }}

      - shell: bash
        run: |
          source ci/rust-version.sh stable
          rustup component add clippy --toolchain "$rust_stable"
          scripts/cargo-clippy-stable.sh

  clippy-nightly:
    needs: setup-status
    strategy:
      matrix:
        os:
          - macos-latest-large
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: mozilla-actions/sccache-action@v0.0.3
        with:
          version: "v0.5.4"

      - shell: bash
        run: .github/scripts/cargo-clippy-before-script.sh ${{ runner.os }}

      - shell: bash
        run: |
          source ci/rust-version.sh nightly
          rustup component add clippy --toolchain "$rust_nightly"
          scripts/cargo-clippy-nightly.sh

  update-status:
    if: always()
    runs-on: ubuntu-latest
    needs:
      - clippy-stable
      - clippy-nightly
    env:
      STATE: ${{ (contains(needs.clippy-stable.result, 'success') && contains(needs.clippy-nightly.result, 'success')) && 'success' || 'failure' }}
    steps:
      - uses: actions/github-script@v7
        with:
          result-encoding: string
          retries: 3
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              context: "macos-clippy",
              description: "triggered by buildkite",
              sha: "${{ github.event.inputs.sha }}",
              state: process.env.STATE,
              target_url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            })
