name: crate-check

on:
  push:
    branches:
      - master
    paths:
      - "**/Cargo.toml"
      - ".github/workflows/crate-check.yml"
      - "./ci/check-crates.sh"
      - "./ci/buildkite-crates.yml"
  pull_request:
    branches:
      - master
    paths:
      - "**/Cargo.toml"
      - ".github/workflows/crate-check.yml"
      - "./ci/check-crates.sh"
      - "./ci/buildkite-crates.yml"

jobs:
  crate-publish-test:
    if: github.repository == 'anza-xyz/agave'
    runs-on: ubuntu-latest
    steps:
      - name: Test crate publishing
        uses: "buildkite/trigger-pipeline-action@v2.2.0"
        with:
          buildkite_api_access_token: ${{ secrets.TRIGGER_BK_BUILD_TOKEN }}
          pipeline: "anza/agave-crates"
          branch: "${{ github.ref_name }}"
          build_env_vars: '{
              "TRIGGERED_BUILDKITE_TAG": "${{ github.ref_name }}",
              "CRATE_PUBLISH_TEST": "true"
            }'
          commit: "HEAD"
          message: ":github: Triggered from crate-check GitHub Action"

  check:
    name: crate check
    if: github.repository == 'anza-xyz/agave'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get commit range (push)
        if: ${{ github.event_name == 'push' }}
        run: |
          echo "COMMIT_RANGE=${{ github.event.before }}..$GITHUB_SHA" >> $GITHUB_ENV

      - name: Get commit range (pull_request)
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "COMMIT_RANGE=${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV

      - name: Setup Rust
        shell: bash
        run: |
          source ci/rust-version.sh stable
          rustup default $rust_stable

      - name: Install toml-cli
        shell: bash
        run: |
          cargo install toml-cli

      - run: |
          ci/check-crates.sh

  error_reporting:
    needs:
      - check
    if: failure() && github.event_name == 'push'
    uses: ./.github/workflows/error-reporting.yml
    secrets:
      WEBHOOK: ${{ secrets.SLACK_ERROR_REPORTING_WEBHOOK }}
