name: Pull Request

on:
  pull_request:
    branches:
      - master
      - v[0-9]+.[0-9]+

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  setup:
    if: github.repository_owner == 'anza-xyz'
    runs-on: ubuntu-24.04
    outputs:
      runner: "ubuntu-24.04"
    steps:
      - run: "true"

  sanity:
    needs: setup
    if: github.repository_owner == 'anza-xyz'
    runs-on: ${{ needs.setup.outputs.runner }}
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Pre-command
        uses: ./.github/actions/pre-command
      - run: ci/docker-run-default-image.sh ci/test-sanity.sh

  shellcheck:
    needs: setup
    if: github.repository_owner == 'anza-xyz'
    runs-on: ${{ needs.setup.outputs.runner }}
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Pre-command
        uses: ./.github/actions/pre-command
      - run: ci/shellcheck.sh

  check:
    needs: [setup, sanity, shellcheck]
    if: github.repository_owner == 'anza-xyz'
    runs-on: ${{ needs.setup.outputs.runner }}
    timeout-minutes: 40
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Pre-command
        uses: ./.github/actions/pre-command
      - run: ci/docker-run-default-image.sh ci/test-checks.sh

  feature-check:
    needs: [setup, sanity, shellcheck]
    if: github.repository_owner == 'anza-xyz'
    runs-on: ${{ needs.setup.outputs.runner }}
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        part: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Pre-command
        uses: ./.github/actions/pre-command
      - run: ci/docker-run-default-image.sh ci/feature-check/test-feature.sh ${{ matrix.part }}/${{ strategy.job-total }}

  feature-check-dev-bins:
    needs: [setup, sanity, shellcheck]
    if: github.repository_owner == 'anza-xyz'
    runs-on: ${{ needs.setup.outputs.runner }}
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Pre-command
        uses: ./.github/actions/pre-command
      - run: ci/docker-run-default-image.sh ci/feature-check/test-feature-dev-bins.sh

  miri:
    needs: [setup, sanity, shellcheck]
    if: github.repository_owner == 'anza-xyz'
    runs-on: ${{ needs.setup.outputs.runner }}
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Pre-command
        uses: ./.github/actions/pre-command
      - run: ci/docker-run-default-image.sh ci/test-miri.sh

  frozen-abi:
    needs: [setup, sanity, shellcheck]
    if: github.repository_owner == 'anza-xyz'
    runs-on: ${{ needs.setup.outputs.runner }}
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Pre-command
        uses: ./.github/actions/pre-command
      - run: ci/docker-run-default-image.sh ci/test-frozen-abi.sh

  stable:
    needs:
      [setup, check, feature-check, feature-check-dev-bins, miri, frozen-abi]
    if: github.repository_owner == 'anza-xyz'
    runs-on: ${{ needs.setup.outputs.runner }}
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        part: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Pre-command
        uses: ./.github/actions/pre-command
      - run: ci/docker-run-default-image.sh ci/stable/run-partition.sh ${{ matrix.part }} ${{ strategy.job-total }}

  dev-bins:
    needs:
      [setup, check, feature-check, feature-check-dev-bins, miri, frozen-abi]
    if: github.repository_owner == 'anza-xyz'
    runs-on: ${{ needs.setup.outputs.runner }}
    timeout-minutes: 40
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Pre-command
        uses: ./.github/actions/pre-command
      - run: ci/docker-run-default-image.sh cargo nextest run --profile ci --manifest-path ./dev-bins/Cargo.toml

  local-cluster:
    needs:
      [setup, check, feature-check, feature-check-dev-bins, miri, frozen-abi]
    if: github.repository_owner == 'anza-xyz'
    runs-on: ${{ needs.setup.outputs.runner }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        part: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Pre-command
        uses: ./.github/actions/pre-command
      - run: ci/docker-run-default-image.sh ci/stable/run-local-cluster-partially.sh ${{ matrix.part }} ${{ strategy.job-total }}

  doctest:
    needs:
      [setup, check, feature-check, feature-check-dev-bins, miri, frozen-abi]
    if: github.repository_owner == 'anza-xyz'
    runs-on: ${{ needs.setup.outputs.runner }}
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Pre-command
        uses: ./.github/actions/pre-command
      - run: ci/docker-run-default-image.sh ci/test-docs.sh

  localnet:
    needs:
      [setup, check, feature-check, feature-check-dev-bins, miri, frozen-abi]
    if: github.repository_owner == 'anza-xyz'
    runs-on: ${{ needs.setup.outputs.runner }}
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Pre-command
        uses: ./.github/actions/pre-command
      - run: ci/docker-run-default-image.sh ci/stable/run-localnet.sh

  stable-sbf:
    needs: [setup, stable, dev-bins, local-cluster, doctest, localnet]
    if: github.repository_owner == 'anza-xyz'
    runs-on: ${{ needs.setup.outputs.runner }}
    timeout-minutes: 35
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Pre-command
        uses: ./.github/actions/pre-command
      - run: ci/docker-run-default-image.sh ci/test-stable-sbf.sh

  shuttle:
    needs: [setup, stable, dev-bins, local-cluster, doctest, localnet]
    if: github.repository_owner == 'anza-xyz'
    runs-on: ${{ needs.setup.outputs.runner }}
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Pre-command
        uses: ./.github/actions/pre-command
      - run: ci/docker-run-default-image.sh ci/test-shuttle.sh

  coverage:
    needs: [setup, stable, dev-bins, local-cluster, doctest, localnet]
    if: github.repository_owner == 'anza-xyz'
    runs-on: ${{ needs.setup.outputs.runner }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        part: [1, 2, 3]
    env:
      FETCH_CODECOV_ENVS: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Pre-command
        uses: ./.github/actions/pre-command
      - run: ci/docker-run-default-image.sh ci/coverage/part-${{ matrix.part }}.sh
