name: Spellcheck

on:
  push:
    branches:
      - master
      - v[0-9]+.[0-9]+
  pull_request:
    branches:
      - master
      - v[0-9]+.[0-9]+
    paths:
      - "**/*.rs"
      - "**/*.md"
      - ".github/workflows/spellcheck.yml"
      - "_typos.toml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  spellcheck:
    if: github.repository == 'anza-xyz/agave'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run typos
        uses: crate-ci/typos@v1.26.0
        with:
          # Initially test on a few smaller crates
          files: |
            clap-utils/**/*.rs
            clap-v3-utils/**/*.rs
            client-test/**/*.rs
            **/*.md
